apiVersion: v1
kind: ConfigMap
metadata:
  name: amd-deployment-template
  namespace: {{ .Release.Namespace }}
  labels:
    group: apps
    version: v1
    kind: Deployment
  annotations:
    primus-safe.gpu.resource.name: "amd.com/gpu"
    # The main container name should match the configuration defined in the template below
    primus-safe.main.container: main
data:
 template: |
   apiVersion: apps/v1
   kind: Deployment
   spec:
     progressDeadlineSeconds: 10800
     template:
       spec:
         dnsPolicy: ClusterFirstWithHostNet
         initContainers:
           - name: preprocess
             image: {{ .Values.repository }}/preprocess:{{ .Values.preprocess.tag }}
             imagePullPolicy: IfNotPresent
             command: ["/bin/sh", "-c", "cp -r /preprocess/* /shared-data/"]
             securityContext:
               capabilities:
                 add: [ "IPC_LOCK" ]
             resources:
               limits:
                 cpu: 1000m
                 memory: 128Mi
             volumeMounts:
             - name: shared-data
               mountPath: /shared-data
         containers:
           - name: main
             imagePullPolicy: IfNotPresent
             env:
               - name: NCCL_SOCKET_IFNAME
                 value: "{{ .Values.net.nccl_socket_ifname }}"
               - name: GLOO_SOCKET_IFNAME
                 value: "{{ .Values.net.nccl_socket_ifname }}"
               - name: NCCL_IB_HCA
                 value: "{{ .Values.net.nccl_ib_hca }}"
               - name: NCCL_DEBUG
                 value: "INFO"
               - name: NCCL_IB_DISABLE
                 value: "0"
               - name: NCCL_IB_TIMEOUT
                 value: "22"
               - name: NCCL_IB_QPS_PER_CONNECTION
                 value: "8"
               - name: NCCL_IB_RETRY_CNT
                 value: "12"
               - name: NCCL_NVLS_ENABLE
                 value: "0"
               - name: NCCL_SOCKET_FAMILY
                 value: "AF_INET"
               - name: POD_IP
                 valueFrom:
                   fieldRef:
                     fieldPath: status.podIP
             securityContext:
               capabilities:
                 add: [ "IPC_LOCK", "SYS_PTRACE", "SYS_RESOURCE"]
             volumeMounts:
               - name: sugaku-volume
                 mountPath: /dev/shm
               - name: varlog
                 mountPath: /var/log
               - name: shared-data
                 mountPath: /shared-data
         volumes:
           - name: varlog
             hostPath:
               path: /var/log
           - name: shared-data
             emptyDir: {}
         imagePullSecrets:
           - name: {{ .Release.Name }}-image
         terminationGracePeriodSeconds: 10
         restartPolicy: Always
         schedulerName: kube-scheduler-plugins