#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-3"
    helm.sh/hook-delete-policy: before-hook-creation
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  users:
    - name: postgres
    - name: {{ .Release.Name }}
      databases:
        - "primus-safe-db"
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              storageClassName: {{ .Values.global.storage_class }}
              accessModes:
                - {{ if eq .Values.global.storage_class "juicefs" }}ReadWriteMany{{ else }}ReadWriteOnce{{ end }}
              resources:
                requests:
                  storage: 1024Gi
  instances:
    - dataVolumeClaimSpec:
        storageClassName: {{ .Values.global.storage_class }}
        accessModes:
          - {{ if eq .Values.global.storage_class "juicefs" }}ReadWriteMany{{ else }}ReadWriteOnce{{ end }}
        resources:
          requests:
            storage: 500Gi
      name: db
      replicas: 2
  monitoring:
    pgmonitor:
      exporter:
        image: ""
  port: 5432
  postgresVersion: 17