apiVersion: v2
name: primus-lens-fluent-operator
description: Fluent Operator wrapper chart
type: application
version: 1.0.0
appVersion: "3.1.0"

dependencies:
  - name: fluent-operator
    version: "3.1.0"
    repository: https://fluent.github.io/helm-charts
