#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

net:
  nccl_socket_ifname: "eno0"
  nccl_ib_hca: "rdma0,rdma1,rdma2,rdma3,rdma4,rdma5,rdma6,rdma7"
  rdma_name: "rdma/hca"
apiserver:
  image: "apiserver:202510091730"
  replicas: 1
  cpu: 2000m
  memory: 4Gi
resource_manager:
  image: "resource-manager:202510091730"
  replicas: 1
  cpu: 2000m
  memory: 4Gi
job_manager:
  image: "job-manager:202510091730"
  replicas: 1
  cpu: 2000m
  memory: 4Gi
webhooks:
  image: "webhooks:202510091730"
  replicas: 1
  cpu: 2000m
  memory: 4Gi
web:
  image: "primus-safe-web:1.6.17"
  replicas: 1
  cpu: 2000m
  memory: 4Gi
preprocess:
  image: "preprocess:202510011436"
db:
  enable: true
  storage_class: "local-path"
opensearch:
  enable: true
  prefix: "node-"
  secret: "primus-lens-logs-admin-password"
  secret_namespace: "primus-lens"
  secret_path: "/etc/secrets/opensearch"
  endpoint: "primus-lens-logs-nodes.primus-lens.svc.cluster.local:9200"
ssh:
  enable: false
user:
  token_required: false
workspace:
  mem_reserve_percent: 0.05
  cpu_reserve_percent: 0.1
  ephemeral_store_reserve_percent: 0.05
s3:
  enable: false
  bucket: "juicefs"
  secret: "juicefs-secret"
  secret_namespace: "juicefs-csi"
  secret_path: "/etc/secrets/s3"
  endpoint: "http://s3.safe.primus.ai"
addon:
  default: cert-manager.v1.17.2,training-operator.1.9.2,network-operator.25.4.0,kube-scheduler-plugins-0.38.1
global:
  domain: "safe-primus.ai"
  sub_domain: "tw325"
