net:
  nccl_socket_ifname: "ens51f0"
  nccl_ib_hca: "bnxt_re0,bnxt_re1,bnxt_re2,bnxt_re3,bnxt_re4,bnxt_re5,bnxt_re6,bnxt_re7"
  rdma_name: "rdma/hca"
apiserver:
  image: "apiserver:202508271650"
  replicas: 1
resource_manager:
  image: "resource-manager:202508252300"
  replicas: 1
job_manager:
  image: "job-manager:202508211040"
  replicas: 1
webhooks:
  image: "webhooks:202508271650"
  replicas: 1
preprocess:
  image: "preprocess:202508251402"
preflight:
  image: "preflight:202507301344"
diagnose:
  image: "diagnose:202508311614"
db:
  enable: true
  storage_class: "juicefs"
log:
  enable: true
ssh:
  enable: false
user:
  enable_authority: true
workspace:
  mem_reserve_percent: 0.1
  cpu_reserve_percent: 0.1
  ephemeral_store_reserve_percent: 0.1
s3:
  enable: true
  endpoint: "http://s3.safe.primus.ai"
  bucket: "juicefs"
  secret: "juicefs-secret"
  secret_namespace: "juicefs-csi"
addon:
  default: cert-manager.v1.17.2,training-operator.1.9.2,network-operator.25.4.0
