crypto:
  enable: true
  key: UHJpbXVzU2FmZTEyMzQ1Ngo=
workspace:
  mem_reserve_percent: 0.02
  cpu_reserve_percent: 0.06
  ephemeral_store_reserve_percent: 0.1
workload:
  max_ephemeral_store_percent: 0.6
repository: "docker.io/primussafe"
resource_manager:
  replicas: 2
  tag: "latest"
apiserver:
  replicas: 2
  tag: "latest"
job_manager:
  replicas: 2
  tag: "latest"
webhooks:
  replicas: 2
  tag: "latest"
node_agent:
  tag: "latest"