crypto:
  enable: true
  key: UHJpbXVzU2FmZTEyMzQ1Ngo=
workspace:
  mem_reserve_percent: 0.02
  cpu_reserve_percent: 0.06
  ephemeral_store_reserve_percent: 0.1
workload:
  max_ephemeral_store_percent: 0.6
repository: docker.io/primussafe
stroageClass: default
resource_manager:
  replicas: 1
  tag: "latest"
  
