crypto:
  enable: true
  key: UHJpbXVzU2FmZTEyMzQ1Ngo=
  path: /etc/secrets
workspace:
  mem_reserve_percent: 0.02
  cpu_reserve_percent: 0.06
  ephemeral_store_reserve_percent: 0.1
workload:
  max_ephemeral_store_percent: 0.6
net:
  nccl_socket_ifname: "ens51f0"
  nccl_ib_hca: "bnxt_re0,bnxt_re1,bnxt_re2,bnxt_re3,bnxt_re4,bnxt_re5,bnxt_re6,bnxt_re7"
repository: "docker.io/primussafe"
resource_manager:
  replicas: 2
  tag: "latest"
apiserver:
  replicas: 2
  tag: "latest"
job_manager:
  replicas: 2
  tag: "latest"
webhooks:
  replicas: 2
  tag: "latest"
node_agent:
  tag: "latest"