net:
  nccl_socket_ifname: "enp49s0f0np0"
  nccl_ib_hca: "bnxt_re0,bnxt_re1,bnxt_re2,bnxt_re3,bnxt_re4,bnxt_re5,bnxt_re7,bnxt_re8"
  rdma_name: "rdma/hca"
apiserver:
  image: "apiserver:202509231600"
  replicas: 2
resource_manager:
  image: "resource-manager:202509231600"
  replicas: 2
job_manager:
  image: "job-manager:202509231600"
  replicas: 2
webhooks:
  image: "webhooks:202509231600"
  replicas: 2
preprocess:
  image: "preprocess:202509092311"
preflight:
  image: "diagnose_single:202509131410"
diagnose:
  image: "diagnose_multi:202509121700"
console:
  image: "primus-safe-web:1.5.0"
  replicas: 2
db:
  enable: true
  storage_class: "rbd"
log:
  enable: true
ssh:
  enable: false
user:
  token_required: false
workspace:
  mem_reserve_percent: 0.05
  cpu_reserve_percent: 0.1
  ephemeral_store_reserve_percent: 0.05
s3:
  enable: false
  endpoint: "http://s3.safe.primus.ai"
  bucket: "juicefs"
  secret: "juicefs-secret"
  secret_namespace: "juicefs-csi"
addon:
  default: cert-manager.v1.17.2,training-operator.1.9.2,network-operator.25.4.0
global:
  domain: "safe-primus.ai"
  sub_domain: "vultr"

