crypto:
  enable: false
  mount_path: /etc/secrets
workspace:
  mem_reserve_percent: 0.02
  cpu_reserve_percent: 0.06
  ephemeral_store_reserve_percent: 0.1
workload:
  max_ephemeral_store_percent: 0.6
net:
  nccl_socket_ifname: "eno0"
  nccl_ib_hca: "rdma0,rdma1,rdma2,rdma3,rdma4,rdma5,rdma6,rdma7"
  rdma_name: "rdma/hca"
repository: "docker.io/primussafe"
k8s:
  enable_health_check: true
  enable_leader_election: true
apiserver:
  port: 8088
  health_port: 8082
  tag: "202506241000"
  replicas: 1
  cpu: "1000m"
  memory: 2Gi
resource_manager:
  health_port: 8081
  tag: "202506241000"
  replicas: 1
  cpu: "1000m"
  memory: 2Gi
job_manager:
  health_port: 8083
  tag: "202506231900"
  replicas: 1
  cpu: "1000m"
  memory: 2Gi
webhooks:
  port: 8084
  health_port: 8085
  tag: "202506241000"
  replicas: 1
  cpu: "1000m"
  memory: 2Gi
preprocess:
  tag: "202506152300"
db:
  enable: false
  secret: "primus-safe-pguser-primus-safe"
  mount_path: "/etc/secrets/db"
  ssl_mode: "require"
  max_open_conns: 100
  max_idle_conns: 10
  max_life_time_second: 600
  max_idle_time_second: 100
  connect_timeout_second: 10
  request_timeout_second: 20
log:
  enable: false
  secret: "primus-safe-logs-admin-password"
  mount_path: "/etc/secrets/log"
  endpoint: "logs-nodes.primus-safe.svc.cluster.local:9200"
  prefix: "node-"
ssh:
  port: 2222
  enable: true
  ingress_ip: 10.235.192.64
  mount_path: "/etc/secrets/ssh"
ops_job:
  ttl_second: 300
  timeout_second: 3600
  batch_count: 1
  available_ratio: 0.98
fault:
  addon_id: "501"