crypto:
  enable: true
  mount_path: /etc/secrets
workspace:
  mem_reserve_percent: 0.02
  cpu_reserve_percent: 0.06
  ephemeral_store_reserve_percent: 0.1
workload:
  max_ephemeral_store_percent: 0.6
net:
  nccl_socket_ifname: "ens51f0"
  nccl_ib_hca: "bnxt_re0,bnxt_re1,bnxt_re2,bnxt_re3,bnxt_re4,bnxt_re5,bnxt_re6,bnxt_re7"
  rdma_name: "rdma/hca"
repository: "docker.io/primussafe"
k8s:
  enable_health_check: true
  enable_leader_election: true
apiserver:
  port: 8088
  health_port: 8082
  image: "apiserver:202507031400"
  replicas: 1
  cpu: "2000m"
  memory: 4Gi
resource_manager:
  health_port: 8081
  image: "resource-manager:202507072200"
  replicas: 1
  cpu: "2000m"
  memory: 4Gi
job_manager:
  health_port: 8083
  image: "job-manager:202507031400"
  replicas: 1
  cpu: "2000m"
  memory: 4Gi
webhooks:
  port: 8084
  health_port: 8085
  image: "webhooks:20507061240"
  replicas: 1
  cpu: "2000m"
  memory: 4Gi
preprocess:
  image: "preprocess:202506152300"
db:
  enable: true
  dbname: "primus-safe-db"
  storage_class: "juicefs"
  mount_path: "/etc/secrets/db"
  ssl_mode: "require"
  max_open_conns: 100
  max_idle_conns: 10
  max_life_time_second: 600
  max_idle_time_second: 100
  connect_timeout_second: 10
  request_timeout_second: 20
log:
  enable: true
  secret: "primus-lens-logs-admin-password"
  secret_namespace: "primus-lens"
  mount_path: "/etc/secrets/log"
  endpoint: "primus-lens-logs-nodes.primus-lens.svc.cluster.local:9200"
  prefix: "node-"
ssh:
  enable: true
  port: 2222
  mount_path: "/etc/secrets/ssh"
s3:
  enable: true
  endpoint: "http://s3.safe.primus.ai"
  bucket: "juicefs"
  secret: "juicefs-secret"
  secret_namespace: "juicefs-csi"
  mount_path: "/etc/secrets/s3"
ops_job:
  ttl_second: 300
  timeout_second: 3600
  batch_count: 1
  available_ratio: 0.98
fault:
  addon_id: "501"