net:
  nccl_socket_ifname: "ens51f0"
  nccl_ib_hca: "bnxt_re0,bnxt_re1,bnxt_re2,bnxt_re3,bnxt_re4,bnxt_re5,bnxt_re6,bnxt_re7"
  rdma_name: "rdma/hca"
apiserver:
  image: "apiserver:202507222200"
  replicas: 1
resource_manager:
  image: "resource-manager:202507222200"
  replicas: 1
job_manager:
  image: "job-manager:202507222200"
  replicas: 1
webhooks:
  image: "webhooks:202507222200"
  replicas: 1
preprocess:
  image: "preprocess:202506152300"
preflight:
  image: "preflight:202507221745"
db:
  enable: true
  storage_class: "juicefs"
log:
  enable: true
ssh:
  enable: false
s3:
  enable: true
  endpoint: "http://s3.safe.primus.ai"
  bucket: "juicefs"
  secret: "juicefs-secret"
  secret_namespace: "juicefs-csi"
