net:
  nccl_socket_ifname: "enp49s0f0np0"
  nccl_ib_hca: "bnxt_re0,bnxt_re1,bnxt_re2,bnxt_re3,bnxt_re4,bnxt_re5,bnxt_re7,bnxt_re8"
  rdma_name: "rdma/hca"
apiserver:
  image: "apiserver:202509090905"
  replicas: 1
resource_manager:
  image: "resource-manager:202509090905"
  replicas: 1
job_manager:
  image: "job-manager:202509090905"
  replicas: 1
webhooks:
  image: "webhooks:202509090905"
  replicas: 1
preprocess:
  image: "preprocess:202508251402"
preflight:
  image: "preflight:202509031707"
diagnose:
  image: "diagnose:202509082317"
console:
  image: "primus-safe-web:1.3.17"
  replicas: 1
db:
  enable: true
  storage_class: "rbd"
log:
  enable: true
ssh:
  enable: false
user:
  token_required: false
  default_workspace: safe-cluster-dev
workspace:
  mem_reserve_percent: 0.06
  cpu_reserve_percent: 0.1
  ephemeral_store_reserve_percent: 0.05
s3:
  enable: false
  endpoint: "http://s3.safe.primus.ai"
  bucket: "juicefs"
  secret: "juicefs-secret"
  secret_namespace: "juicefs-csi"
addon:
  default: cert-manager.v1.17.2,training-operator.1.9.2,network-operator.25.4.0
global:
  domain: "safe-primus.ai"
  sub_domain: "vultr"

