net:
  nccl_socket_ifname: "eno0"
  nccl_ib_hca: "rdma0,rdma1,rdma2,rdma3,rdma4,rdma5,rdma6,rdma7"
  rdma_name: "rdma/hca"
apiserver:
  image: "apiserver:202509231600"
  replicas: 1
  cpu: 2000m
  memory: 4Gi
resource_manager:
  image: "resource-manager:202509231600"
  replicas: 1
  cpu: 2000m
  memory: 4Gi
job_manager:
  image: "job-manager:202509231600"
  replicas: 1
  cpu: 2000m
  memory: 4Gi
webhooks:
  image: "webhooks:202509231600"
  replicas: 1
  cpu: 2000m
  memory: 4Gi
web:
  image: "primus-safe-web:1.5.7"
  replicas: 1
  cpu: 2000m
  memory: 4Gi
preprocess:
  image: "preprocess:202509092311"
preflight:
  image: "diagnose_single:202509131410"
diagnose:
  image: "diagnose_multi:202509121700"
db:
  enable: true
  storage_class: "local-path"
log:
  enable: true
ssh:
  enable: false
user:
  token_required: false
workspace:
  mem_reserve_percent: 0.05
  cpu_reserve_percent: 0.1
  ephemeral_store_reserve_percent: 0.05
s3:
  enable: false
  endpoint: "http://s3.safe.primus.ai"
  bucket: "juicefs"
  secret: "juicefs-secret"
  secret_namespace: "juicefs-csi"
addon:
  default: cert-manager.v1.17.2,training-operator.1.9.2,network-operator.25.4.0,kube-scheduler-plugins-0.38.1
global:
  domain: "safe-primus.ai"
  sub_domain: "oci"

