global:
  debug: ${DEBUG}                                            ## 是否开启 debug 模式
  tls_verify: ${GLOBAL_TLS_VERIFY}                           ## 是否开启全局 TLS 验证
  policy_path: ""
  insecure_policy: true
  registries_dir_path: ""
  override_arch: ${OVERRIDE_ARCH}                            ## 此处为指定同步镜像的架构，如果不指定，则为空
  override_os: ${OVERRIDE_OS}                                ## 此处为指定同步镜像的操作系统，如果不指定，则为空
  override_variant: ""
  command_timeout: ${COMMAND_TIMEOUT}                        ## 此处为同步镜像的超时时间
  registries_conf_path: ""
  tmp_dir: ""

deprecated_tls_verify:
  tls_verify: false

src_image:
  docker_image_options:
    global: {}
    shared: 
      auth_file_path: ""
    deprecated_tls_verify: {}
    auth_file_path: ${AUTH_FILE_PATH}                        ## 源镜像仓库的认证文件路径
    creds_option: ""
    username: ${SOURCE_USERNAME}                          
    password: ${SOURCE_PASSWORD}                            
    registry_token: ""
    docker_cert_path: ""
    tls_verify: ${SOURCE_TLS_VERIFY}                         ## 源镜像仓库是否开启 TLS 验证
    no_creds: false
  shared_blob_dir: ""
  docker_daemon_host: ""

dest_image:
  image_options:
    docker_image_options:
      global: {}
      shared: 
        auth_file_path: ""
      deprecated_tls_verify: {}
      auth_file_path: ${AUTH_FILE_PATH}                      ## 目标镜像仓库的认证文件路径
      creds_option: ""
      username: ${DESTINATION_USERNAME}                    
      password: ${DESTINATION_PASSWORD}                     
      registry_token: ""
      docker_cert_path: ""
      tls_verify: ${DESTINATION_TLS_VERIFY}                  ## 目标镜像仓库是否开启 TLS 验证
      no_creds: false
    shared_blob_dir: ""
    docker_daemon_host: ""
  dir_force_compression: false                               ## 是否强制压缩,默认为 false, 该操作只能在 dest 指定为 dir 时生效
  dir_force_decompression: false                             ## 是否强制解压,默认为 false, 该操作只能在 dest 指定为 dir 时生效
  oci_accept_uncompressed_layers: false
  compression_format: "gzip"
  compression_level: 5
  precompute_digests: false
  image_dest_flag_prefix: ""

retry_opts:
  max_retry: 3
  delay: 1

## 签名暂时不用
remove_signatures: false
sign_by_fingerprint: ""
sign_by_sigstore_param_file: ""
sign_by_sigstore_private_key: ""
sign_passphrase_file: ""
format: ""                                                   ## 此处为修改镜像的格式，但是，如果存在签名的镜像，则此处必须为空，否则会因为签名的 MIME 不同导致同步失败
source: ${SOURCE_TYPE}                                       ## docker or dir
destination: ${DESTINATION_TYPE}                             ## docker or dir
digest_file: ""
scoped: false
all: ${SYNC_ALL_ARCH}                                        ## 是否同步所有 os/arch 版本的镜像
dry_run: false
preserve_digests: false
keep_going: false
append_suffix: ""
upstream_domain: ${UPSTREAM_DOMAIN}                                  ## 上传数据的域名信息