{{- if and (eq (include "primus-lens.management.enabled" .) "true") .Values.management.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "primus-lens.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "primus-lens.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.management.api.service.type }}
  ports:
  - port: {{ .Values.management.api.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "primus-lens.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}

