apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: primus-lens
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default
  namespace: primus-lens
spec:
  secretName: default
  dnsNames:
    - vultr.lens-primus.ai
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  duration: 2160h # 90 days
  renewBefore: 12h