#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-resource-manager
  namespace: {{ .Release.Namespace }}
  labels:
    primus-safe-app-name: resource-manager
    app: {{ .Release.Name }}-resource-manager
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.resource_manager.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-resource-manager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-resource-manager
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: NotIn
                    values:
                      - "true"
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}-resource-manager
          image: {{ .Values.global.image_registry }}/primussafe/{{ .Values.resource_manager.image }}
          imagePullPolicy: Always
          command: ["/bin/sh", "/opt/primus-safe/resource-manager/run.sh"]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: server-config
              mountPath: /opt/primus-safe/resource-manager/config
              readOnly: true
            {{- if .Values.db.enable }}
            - name: db-secret
              mountPath: {{ default "/etc/secrets/db" (default .Values.db).secret_path }}
              readOnly: true
            {{- end }}
            {{- if .Values.s3.enable }}
            - name: s3-secret
              mountPath: {{ .Values.s3.secret_path }}
              readOnly: true
            {{- end }}
            {{- if and .Values.opensearch.enable (or (empty .Values.opensearch.username) (empty .Values.opensearch.password)) }}
            - name: opensearch-secret
              mountPath: {{ .Values.opensearch.secret_path }}
              readOnly: true
            {{- end }}
            {{- if and .Values.notification .Values.notification.email .Values.notification.email.smtp_host }}
            - name: notification-secret
              mountPath: /etc/secrets/notification
              readOnly: true
            {{- end }}
          {{- if default true (default .Values.k8s).enable_health_check }}
          ports:
            - containerPort: {{ default 8081 (default .Values.resource_manager).health_port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ default 8081 (default .Values.resource_manager).health_port }}
            initialDelaySeconds: 20
            periodSeconds: 2
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ default 8081 (default .Values.resource_manager).health_port }}
            initialDelaySeconds: 20
            periodSeconds: 2
            timeoutSeconds: 3
          {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resource_manager.cpu }}
              memory: {{ .Values.resource_manager.memory }}
            requests:
              cpu: {{ .Values.resource_manager.cpu }}
              memory: {{ .Values.resource_manager.memory }}
      {{- if .Values.global.image_pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.global.image_pull_secret }}
      {{- end }}
      volumes:
        {{- if .Values.db.enable }}
        - name: db-secret
          secret:
            secretName: {{ .Release.Name }}-pguser-{{ .Release.Name }}
        {{- end }}
        {{- if .Values.s3.enable }}
        - name: s3-secret
          secret:
            secretName: {{ .Values.s3.secret }}
        {{- end }}
        {{- if and .Values.opensearch.enable (or (empty .Values.opensearch.username) (empty .Values.opensearch.password)) }}
        - name: opensearch-secret
          secret:
            secretName: {{ .Values.opensearch.secret }}
        {{- end }}
        {{- if and .Values.notification .Values.notification.email .Values.notification.email.smtp_host }}
        - name: notification-secret
          secret:
            secretName: {{ .Release.Name }}-notification
        {{- end }}
        - name: server-config
          configMap:
            name: {{ .Release.Name }}-resource-manager
      terminationGracePeriodSeconds: 10
      priorityClassName: system-cluster-critical
      restartPolicy: Always
