{{/*
Grafana Data Sources
Defines data sources for Grafana (VictoriaMetrics, PostgreSQL, etc.)
*/}}
{{- if .Values.grafana.enabled }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: primus-lens-victoriametrics
  namespace: {{ include "primus-lens.namespace" . }}
  labels:
    {{- include "primus-lens.labels" . | nindent 4 }}
    dashboards: "primus-lens"
spec:
  instanceSelector:
    matchLabels:
      dashboards: "primus-lens"
  
  datasource:
    name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://vmselect-primus-lens-vmcluster.{{ include "primus-lens.namespace" . }}.svc.cluster.local:8481/select/0/prometheus
    isDefault: true
    editable: true
    jsonData:
      tlsSkipVerify: true
      timeInterval: "30s"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: primus-lens-postgres
  namespace: {{ include "primus-lens.namespace" . }}
  labels:
    {{- include "primus-lens.labels" . | nindent 4 }}
    dashboards: "primus-lens"
spec:
  instanceSelector:
    matchLabels:
      dashboards: "primus-lens"
  
  datasource:
    name: PostgreSQL
    type: postgres
    access: proxy
    url: {{ include "primus-lens.postgresHost" . }}:5432
    database: primus_lens
    user: primus_lens
    editable: true
    jsonData:
      sslmode: "disable"
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: $__file{/etc/secrets/db/password}
{{- end }}

