server:
  port: 8088
health_check:
  enable: true
  port: 8082
workspace:
  mem_reserve_percent: 0.02
  cpu_reserve_percent: 0.06
  ephemeral_store_reserve_percent: 0.1
workload:
  max_ephemeral_store_percent: 0.6