{{- if and (eq (include "primus-lens.data.enabled" .) "true") .Values.data.gpuResourceExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "primus-lens.fullname" . }}-gpu-resource-exporter
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "primus-lens.labels" . | nindent 4 }}
    app.kubernetes.io/component: gpu-resource-exporter
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    {{- include "primus-lens.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gpu-resource-exporter
{{- end }}

