#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

# The parameters should be modified according to the actual cluster environment.
apiVersion: amd.com/v1
kind: NodeFlavor
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: amd-mi300x-example
spec:
  cpu:
    product: AMD_EPYC_9554
    quantity: "256"
  dataDisk:
    count: 9
    quantity: 7864Gi
    type: nvme
  extendedResources:
    ephemeral-storage: 6695573390Ki
    rdma/hca: 1k
  gpu:
    product: MI300X
    quantity: "8"
    resourceName: amd.com/gpu
  memory: 1584032704Ki
  rootDisk:
    count: 1
    quantity: 7864Gi
    type: nvme
