#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

apiVersion: amd.com/v1
kind: NodeTemplate
metadata:
  name: node-template
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  addOnTemplates:
    - disable-os-upgrade
    - disable-apt-auto-upgrade
    - disable-numa-balancing
    - enable-cpu-performance
    - enable-huge-pages
    - load-amdgpu-module
    - load-rdma-module
    - set-max-sclk
    - sysctl-max-map-count
    - sysctl-ulimit
    - sysctl-inotify
