#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.17.2
  name: workspaces.amd.com
spec:
  group: amd.com
  names:
    kind: Workspace
    listKind: WorkspaceList
    plural: workspaces
    singular: workspace
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              cluster:
                description: The cluster that the workspace belongs to
                type: string
              enablePreempt:
                description: Whether preemption is enabled. If enabled, higher-priority
                  workload will preempt the lower-priority one
                type: boolean
              imageSecrets:
                description: Workspace image secret ID, used for downloading images
                items:
                  description: ObjectReference contains enough information to let
                    you inspect or modify the referred object.
                  properties:
                    apiVersion:
                      description: API version of the referent.
                      type: string
                    fieldPath:
                      description: |-
                        If referring to a piece of an object instead of an entire object, this string
                        should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2].
                        For example, if the object reference is to a container within a pod, this would take on a value like:
                        "spec.containers{name}" (where "name" refers to the name of the container that triggered
                        the event) or if no container name is specified "spec.containers[2]" (container with
                        index 2 in this pod). This syntax is chosen only to have some well-defined way of
                        referencing a part of an object.
                      type: string
                    kind:
                      description: |-
                        Kind of the referent.
                        More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
                      type: string
                    name:
                      description: |-
                        Name of the referent.
                        More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      type: string
                    namespace:
                      description: |-
                        Namespace of the referent.
                        More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
                      type: string
                    resourceVersion:
                      description: |-
                        Specific resourceVersion to which this reference is made, if any.
                        More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
                      type: string
                    uid:
                      description: |-
                        UID of the referent.
                        More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids
                      type: string
                  type: object
                  x-kubernetes-map-type: atomic
                type: array
              isDefault:
                description: Set the workspace as the default workspace (i.e., all
                  users can access it)
                type: boolean
              managers:
                description: User id of the workspace administrator
                items:
                  type: string
                type: array
              nodeFlavor:
                description: The node flavor id of workspace, A workspace supports
                  only one node flavor
                type: string
              queuePolicy:
                description: |-
                  Queuing policy for workloads submitted in this workspace.
                  All workloads currently share the same policy, supports fifo (default) and balance.
                  1. "Fifo" means first-in, first-out: the workload that enters the queue first is served first.
                     If the front workload does not meet the conditions for dispatch, it will wait indefinitely,
                     and other tasks in the queue will also be blocked waiting.
                  2. "Balance" allows any workload that meets the resource conditions to be dispatched,
                     avoiding blockage by the front workload in the queue. However, it is still subject to priority constraints.
                     If a higher-priority task cannot be dispatched, lower-priority tasks will wait.
                type: string
              replica:
                description: The expected number of nodes in the workspace
                type: integer
              scopes:
                description: 'Service modules available in this space. support: Train/Infer/Authoring/CICD,
                  No limitation if not specified'
                items:
                  enum:
                  - Train
                  - Infer
                  - Authoring
                  - CICD
                  type: string
                type: array
              volumes:
                description: Volumes used in this workspace
                items:
                  properties:
                    accessMode:
                      description: access mode, default ReadWriteMany
                      type: string
                    capacity:
                      description: |-
                        The following parameters are used for PVC creation. If using hostPath mounting, they are not required.
                        Capacity size, e.g. 100Gi. This is a required parameter when creating a PVC (PersistentVolumeClaim).
                      type: string
                    hostPath:
                      description: Path on the host to mount. Required when volume
                        type is hostpath
                      type: string
                    id:
                      description: The volume id, which is used to identify the volume.
                        This field is set internally.
                      type: integer
                    mountPath:
                      description: Mount path to be used, equivalent to 'mountPath'
                        in Kubernetes volume mounts.
                      type: string
                    selector:
                      additionalProperties:
                        type: string
                      description: |-
                        selector is a label query over volumes to consider for binding.
                        It cannot be used together with storageClass. If both are set, the selector takes priority
                      type: object
                    storageClass:
                      description: Responsible for automatic PV creation
                      type: string
                    subPath:
                      description: equivalent to 'subPath' in Kubernetes volume mounts
                      type: string
                    type:
                      description: |-
                        The volume type, valid values includes: pfs/hostpath
                        If PFS is configured, a PVC will be automatically created in the workspace.
                      type: string
                  required:
                  - id
                  - mountPath
                  - type
                  type: object
                type: array
            required:
            - cluster
            type: object
          status:
            properties:
              abnormalReplica:
                description: The abnormal node count of workspace
                type: integer
              availableReplica:
                description: The available node count of workspace
                type: integer
              availableResources:
                additionalProperties:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                description: The available resource of workspace
                type: object
              phase:
                description: The status of workspace, e.g. Creating, Running, Abnormal,
                  Deleting
                type: string
              totalResources:
                additionalProperties:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                description: The total resource of workspace
                type: object
              updateTime:
                description: Last update time
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
