apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-apiserver
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.apiserver.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-apiserver
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-apiserver
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: NotIn
                    values:
                      - "true"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Release.Name }}-job-manager
                        - {{ .Release.Name }}-webhooks
                        - {{ .Release.Name }}-resource-manager
                        - {{ .Release.Name }}-web
                topologyKey: kubernetes.io/hostname
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}-apiserver
          image: docker.io/primussafe/{{ .Values.apiserver.image }}
          imagePullPolicy: Always
          command: ["/bin/sh", "/opt/primus-safe/apiserver/run.sh"]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: crypto-secret
              mountPath: {{ default "/etc/secrets/crypto" (default .Values.crypto).mount_path }}
              readOnly: true
            - name: server-config
              mountPath: /opt/primus-safe/apiserver/config
              readOnly: true
            {{- if .Values.db.enable }}
            - name: db-secret
              mountPath: {{ default "/etc/secrets/db" (default .Values.db).mount_path }}
              readOnly: true
            {{- end }}
            {{- if and .Values.log.enable (or (empty .Values.log.username) (empty .Values.log.password)) }}
            - name: log-secret
              mountPath: {{ default "/etc/secrets/log" (default .Values.log).mount_path }}
              readOnly: true
            {{- end }}
            {{- if .Values.ssh.enable }}
            - name: ssh-proxy
              mountPath: {{ default "/etc/secrets/ssh" (default .Values.ssh).mount_path }}
              readOnly: true
            {{- end }}
          ports:
            - containerPort: {{ default 8088 (default .Values.apiserver).port }}
              name: http-port
            {{- if .Values.ssh.enable }}
            - containerPort: {{ default 2222 (default .Values.ssh).port }}
              name: ssh-port
              protocol: TCP
            {{- end }}
          {{- if default true (default .Values.k8s).enable_health_check }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ default 8082 (default .Values.apiserver).health_port }}
            initialDelaySeconds: 20
            periodSeconds: 2
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ default 8082 (default .Values.apiserver).health_port }}
            initialDelaySeconds: 20
            periodSeconds: 2
            timeoutSeconds: 3
          {{- end }}
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 2000m
              memory: 4Gi
      volumes:
        - name: crypto-secret
          secret:
            secretName: {{ .Release.Name }}-crypto
        {{- if .Values.db.enable }}
        - name: db-secret
          secret:
            secretName: {{ .Release.Name }}-pguser-{{ .Release.Name }}
        {{- end }}
        {{- if and .Values.log.enable (or (empty .Values.log.username) (empty .Values.log.password)) }}
        - name: log-secret
          secret:
            secretName: {{ default "primus-lens-logs-admin-password" (default .Values.log).secret }}
        {{- end }}
        {{- if .Values.ssh.enable }}
        - name: ssh-proxy
          secret:
            secretName: {{ .Release.Name }}-ssh-proxy
        {{- end }}
        - name: server-config
          configMap:
            name: {{ .Release.Name }}-apiserver
      imagePullSecrets:
        - name: {{ .Release.Name }}-image
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      terminationGracePeriodSeconds: 10
      priorityClassName: system-cluster-critical
      restartPolicy: Always
