apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-apiserver
spec:
  replicas: {{ .Values.apiserver.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-apiserver
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-apiserver
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: DoesNotExist
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: NotIn
                    values:
                      - "true"
      serviceAccountName: {{ .Release.Name }}-manager
      containers:
        - name: {{ .Release.Name }}-apiserver
          image: {{ .Values.repository }}/apiserver:{{ .Values.apiserver.tag }}
          imagePullPolicy: Always
          command: ["/bin/sh", "/opt/primus-safe/apiserver/run.sh"]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            {{- if .Values.crypto.enable }}
            - name: server-secret
              mountPath: {{ .Values.crypto.path }}
              readOnly: true
            {{- end }}
            - name: server-config
              mountPath: /opt/primus-safe/apiserver/config
              readOnly: true
            {{- if .Values.db.enable }}
            - name: db-secret
              mountPath: {{ .Values.db.mount_path }}
              readOnly: true
            {{- end }}
            {{- if .Values.log.enable }}
            - name: log-secret
              mountPath: {{ .Values.log.mount_path }}
              readOnly: true
            {{- end }}
          ports:
            - containerPort: 8088
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 2
          resources:
            limits:
              cpu: "1000m"
              memory: 2Gi
            requests:
              cpu: "1000m"
              memory: 2Gi
      volumes:
        {{- if .Values.crypto.enable }}
        - name: server-secret
          secret:
            secretName: {{ .Release.Name }}
        {{- end }}
        {{- if .Values.db.enable }}
        - name: db-secret
          secret:
            secretName: {{ .Values.db.secret }}
        {{- end }}
        {{- if .Values.log.enable }}
        - name: log-secret
          secret:
            secretName: {{ .Values.log.secret }}
        {{- end }}
        - name: server-config
          configMap:
            name: {{ .Release.Name }}-apiserver
      imagePullSecrets:
        - name: {{ .Release.Name }}-image
      terminationGracePeriodSeconds: 10
      priorityClassName: system-cluster-critical
      restartPolicy: Always
