apiVersion: v1
kind: Service
metadata:
  name: apiserver-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-apiserver
  ports:
    - protocol: TCP
      port: {{ .Values.apiserver.port }}
      targetPort: {{ .Values.apiserver.port }}
      name: http-port
    {{- if .Values.ssh.enable }}
    - protocol: TCP
      port: {{ .Values.ssh.port }}
      targetPort: {{ .Values.ssh.port }}
      name: ssh-port
    {{- end }}
  type: ClusterIP
