apiVersion: v1
kind: Service
metadata:
  name: apiserver-service
  namespace: primus-safe
spec:
  selector:
    app: primus-safe-apiserver
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP
