apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    higress.io/domain_{{ .Values.global.sub_domain }}.{{ .Values.global.domain }}: "true"
    higress.io/resource-definer: higress
  annotations:
    higress.io/destination: {{ .Release.Name }}-web.{{ .Release.Namespace }}.svc.cluster.local:80
    higress.io/ignore-path-case: "false"
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: higress
  rules:
    - host: {{ .Values.global.sub_domain }}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              resource:
                apiGroup: networking.higress.io
                kind: McpBridge
                name: default
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.global.sub_domain }}.{{ .Values.global.domain }}
      secretName: default