#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webhooks
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-webhooks
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.webhooks.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-webhooks
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-webhooks
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: NotIn
                    values:
                      - "true"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Release.Name }}-job-manager
                        - {{ .Release.Name }}-resource-manager
                        - {{ .Release.Name }}-apiserver
                        - {{ .Release.Name }}-web
                topologyKey: kubernetes.io/hostname
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}-webhooks
          image: {{ .Values.global.image_repository }}/primussafe/{{ .Values.webhooks.image }}
          imagePullPolicy: Always
          command: ["/bin/sh", "/opt/primus-safe/webhooks/run.sh"]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: KEY_NAME
              value: "tls.key"
            - name: CERT_NAME
              value: "tls.crt"
            - name: CA_NAME
              value: "ca.crt"
          volumeMounts:
            - name: server-cert
              mountPath: "/opt/primus-safe/webhooks/cert"
              readOnly: true
            - name: server-config
              mountPath: /opt/primus-safe/webhooks/config
              readOnly: true
          ports:
            - containerPort: {{ default 8084 (default .Values.webhooks).port }}
              protocol: TCP
              name: http-port
          {{- if default true (default .Values.k8s).enable_health_check }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ default 8085 (default .Values.webhooks).health_port }}
            initialDelaySeconds: 20
            periodSeconds: 2
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ default 8085 (default .Values.webhooks).health_port }}
            initialDelaySeconds: 20
            periodSeconds: 2
            timeoutSeconds: 3
          {{- end }}
          resources:
            limits:
              cpu: {{ .Values.webhooks.cpu }}
              memory: {{ .Values.webhooks.memory }}
            requests:
              cpu: {{ .Values.webhooks.cpu }}
              memory: {{ .Values.webhooks.memory }}
      {{- if .Values.global.image_pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.global.image_pull_secret }}
      {{- end }}
      volumes:
        - name: server-config
          configMap:
            name: {{ .Release.Name }}-webhooks
        - name: server-cert
          secret:
            secretName: {{ .Release.Name }}-cert
      terminationGracePeriodSeconds: 10
      priorityClassName: system-cluster-critical
      restartPolicy: Always
