apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-webhooks
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8084
  type: ClusterIP
