global:
  enable_crypto: true
health_check:
  enable: true
  port: 8081
leader_election:
  enable: true
  lock_namespace: primus-safe
workspace:
  mem_reserve_percent: 0.02
  cpu_reserve_percent: 0.06
  ephemeral_store_reserve_percent: 0.1