health_check:
  enable: true
  port: 8081
leader_election:
  enable: false
  lock_namespace: "default"
workspace:
  mem_reserve_percent: 0.02
  cpu_reserve_percent: 0.06
  ephemeral_store_reserve_percent: 0.1