#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    # helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-3"
    helm.sh/hook-delete-policy: before-hook-creation
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  users:
    - name: postgres
    - name: {{ .Release.Name }}
      databases:
        - "primus-safe-db"
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "14"
        repo1-retention-full-type: time
      repos:
        - name: repo1
          schedules:
            differential: 0 2 * * 1-6
            full: 0 2 * * 0
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1024Gi
              storageClassName: {{ .Values.global.storage_class }}
  # To avoid multiple instances on the same node, please add affinity.
  instances:
    - dataVolumeClaimSpec:
        storageClassName: {{ .Values.global.storage_class }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Ti
      name: db
      replicas: 2
      resources:
        limits:
          cpu: 2000m
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 2Gi
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          effective_cache_size: 1GB
          max_connections: "200"
          shared_buffers: 256MB
    leaderLeaseDurationSeconds: 30
    port: 8008
    syncPeriodSeconds: 10
  port: 5432
  postgresVersion: 17