apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "primus-lens.fullname" . }}
  labels:
    {{- include "primus-lens.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "primus-lens.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "primus-lens.serviceAccountName" . }}
    namespace: {{ .Values.global.namespace }}

