{{- if and (eq (include "primus-lens.data.enabled" .) "true") .Values.data.jobs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "primus-lens.fullname" . }}-jobs-data
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "primus-lens.labels" . | nindent 4 }}
    app.kubernetes.io/component: jobs-data
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.data.jobs.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    {{- include "primus-lens.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: jobs-data
{{- end }}

