apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-resource-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-resource-manager
spec:
  replicas: {{ .Values.resource_manager.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-resource-manager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-resource-manager
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: DoesNotExist
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: NotIn
                    values:
                      - "true"
      serviceAccountName: {{ .Release.Name }}-manager
      containers:
        - name: {{ .Release.Name }}-resource-manager
          image: {{ .Values.repository }}/resource-manager:{{ .Values.resource_manager.tag }}
          imagePullPolicy: Always
          command: ["/bin/sh", "/opt/primus-safe/resource-manager/run.sh"]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            {{- if .Values.crypto.enable }}
            - name: crypto-secret
              mountPath: {{ .Values.crypto.mount_path }}
              readOnly: true
            {{- end }}
            - name: server-config
              mountPath: /opt/primus-safe/resource-manager/config
              readOnly: true
            {{- if .Values.db.enable }}
            - name: db-secret
              mountPath: {{ .Values.db.mount_path }}
              readOnly: true
            {{- end }}
            {{- if .Values.s3.enable }}
            - name: s3-secret
              mountPath: {{ .Values.s3.mount_path }}
              readOnly: true
            {{- end }}
          {{- if .Values.k8s.enable_health_check }}
          ports:
            - containerPort: {{ .Values.resource_manager.health_port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.resource_manager.health_port }}
            initialDelaySeconds: 20
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.resource_manager.health_port }}
            initialDelaySeconds: 20
            periodSeconds: 2
          {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resource_manager.cpu }}
              memory: {{ .Values.resource_manager.memory }}
            requests:
              cpu: {{ .Values.resource_manager.cpu }}
              memory: {{ .Values.resource_manager.memory }}
      imagePullSecrets:
      - name: {{ .Release.Name }}-image
      volumes:
        {{- if .Values.crypto.enable }}
        - name: crypto-secret
          secret:
            secretName: {{ .Release.Name }}-crypto
        {{- end }}
        {{- if .Values.db.enable }}
        - name: db-secret
          secret:
            secretName: {{ .Values.db.secret }}
        {{- end }}
        {{- if .Values.s3.enable }}
        - name: s3-secret
          secret:
            secretName: {{ .Values.s3.secret }}
        {{- end }}
        - name: server-config
          configMap:
            name: {{ .Release.Name }}-resource-manager
      terminationGracePeriodSeconds: 10
      priorityClassName: system-cluster-critical
      restartPolicy: Always
