apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-resource-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-resource-manager
spec:
  replicas: {{ .Values.resource_manager.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-resource-manager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-resource-manager
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: DoesNotExist
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: NotIn
                    values:
                      - "true"
      serviceAccountName: {{ .Release.Name }}-manager
      containers:
        - name: {{ .Release.Name }}-resource-manager
          image: {{ .Values.repository }}/resource-manager:{{ .Values.resource_manager.tag }}
          imagePullPolicy: Always
          command: ["/bin/sh", "/opt/primus-safe/resource-manager/run.sh"]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            {{- if .Values.crypto.enable }}
            - name: server-secret
              mountPath: {{ .Values.crypto.path }}
              readOnly: true
            {{- end }}
            - name: server-config
              mountPath: /opt/primus-safe/resource-manager/config
              readOnly: true
            {{- if .Values.db.enable }}
            - name: db-secret
              mountPath: {{ .Values.db.mount_path }}
              readOnly: true
            {{- end }}
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 2
          resources:
            limits:
              cpu: "2000m"
              memory: 4Gi
            requests:
              cpu: "2000m"
              memory: 4Gi
      imagePullSecrets:
      - name: {{ .Release.Name }}-image
      volumes:
        {{- if .Values.crypto.enable }}
        - name: server-secret
          secret:
            secretName: {{ .Release.Name }}
        {{- end }}
        {{- if .Values.db.enable }}
        - name: db-secret
          secret:
            secretName: {{ .Values.db.secret }}
        {{- end }}
        - name: server-config
          configMap:
            name: {{ .Release.Name }}-resource-manager
      terminationGracePeriodSeconds: 10
      priorityClassName: system-cluster-critical
      restartPolicy: Always
