#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  labels:
    primus-safe.display.name: "amd-gpu-operator-charts-v1.4.0"
    app.kubernetes.io/managed-by: Helm
    primus-safe.addon.default: ""
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: amd-gpu-operator-v1.4.0 
spec:
  category: plugin
  description: Kubernetes scheduler plugin framework. 
  url: oci://registry-1.docker.io/primussafe/gpu-operator-charts
  version: v1.4.0
  type: helm
  helmDefaultNamespace: kube-amd-gpu