apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: install-rccl-test
  labels:
    primus-safe.display.name: "install-rccl-test"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  category: Tools
  description: RCCL is designed to be used as a performant backend for downstream applications, particularly AI training and inference workloads, it also has a test suite to benchmark and validate performance
  action: UkVQT19VUkw9Imh0dHBzOi8vZ2l0aHViLmNvbS9ST0NtL3JjY2wtdGVzdHMuZ2l0IgpESVJfTkFNRT0iL3Jvb3QvcmNjbC10ZXN0cyIKaWYgWyAtZCAiJERJUl9OQU1FIiBdOyB0aGVuCiAgZXhpdCAwCmZpCgpkcGtnIC1sIHwgZ3JlcCAtcSBnaXQKaWYgWyAkPyAtbmUgMCBdOyB0aGVuCiAgYXB0LWdldCB1cGRhdGUgPi9kZXYvbnVsbCAmJiBhcHQtZ2V0IC15IGluc3RhbGwgZ2l0ID4vZGV2L251bGwKICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgIGV4aXQgMQogIGZpCmZpCmNkICIvcm9vdCIgJiYgZ2l0IGNsb25lICIkUkVQT19VUkwiID4vZGV2L251bGwKaWYgWyAkPyAtbmUgMCBdOyB0aGVuCiAgZXhpdCAxCmZpCgpjZCAiJERJUl9OQU1FIiB8fCBleGl0IDEKZHBrZyAtbCB8IGdyZXAgLXEgbWFrZQppZiBbICQ/IC1uZSAwIF07IHRoZW4KICBhcHQtZ2V0IHVwZGF0ZSA+L2Rldi9udWxsICYmIGFwdC1nZXQgLXkgaW5zdGFsbCBtYWtlID4vZGV2L251bGwKICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgIGV4aXQgMQogIGZpCmZpCm1ha2UgTVBJPTEgTVBJX0hPTUU9L3Vzci9saWIveDg2XzY0LWxpbnV4LWdudS9vcGVubXBpIE5DQ0xfSE9NRT0vb3B0L3JvY20vID4vZGV2L251bGwKaWYgWyAkPyAtbmUgMCBdOyB0aGVuCiAgZXhpdCAxCmZpCg==