apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: install-babel-stream
  labels:
    primus-safe.display.name: "install-babel-stream"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: dpkg
  category: Tools
  description: BabelStream is an open-source benchmark to measure transfer rates to/from global device memory on GPUs
  extensions:
    action: UkVQT19VUkw9Imh0dHBzOi8vZ2l0aHViLmNvbS9Vb0ItSFBDL0JhYmVsU3RyZWFtLmdpdCIKRElSX05BTUU9Ii9yb290L0JhYmVsU3RyZWFtIgppZiBbICEgLWQgIiRESVJfTkFNRSIgXTsgdGhlbgogIGRwa2cgLWwgfCBncmVwIC1xIGdpdAogIGlmIFsgJD8gLW5lIDAgXTsgdGhlbgogICAgYXB0LWdldCB1cGRhdGUgPi9kZXYvbnVsbCAmJiBhcHQtZ2V0IC15IGluc3RhbGwgZ2l0ID4vZGV2L251bGwKICAgIGlmIFsgJD8gLW5lIDAgXTsgdGhlbgogICAgICBleGl0IDEKICAgIGZpCiAgZmkKICBnaXQgY2xvbmUgIiRSRVBPX1VSTCIgPi9kZXYvbnVsbAogIGlmIFsgJD8gLW5lIDAgXTsgdGhlbgogICAgZXhpdCAxCiAgZmkKZmkKY2QgIiRESVJfTkFNRSIgfHwgZXhpdCAxCmRwa2cgLWwgfCBncmVwIC1xIGNtYWtlCmlmIFsgJD8gLW5lIDAgXTsgdGhlbgogIGFwdC1nZXQgdXBkYXRlID4vZGV2L251bGwgJiYgYXB0LWdldCAteSBpbnN0YWxsIGNtYWtlID4vZGV2L251bGwKICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgIGV4aXQgMQogIGZpCmZpCmNtYWtlIC1CYnVpbGQgLUguIC1ETU9ERUw9aGlwIC1EQ01BS0VfQ1hYX0NPTVBJTEVSPWhpcGNjID4vZGV2L251bGwgJiYgY21ha2UgLS1idWlsZCBidWlsZCA+L2Rldi9udWxsCmlmIFsgJD8gLW5lIDAgXTsgdGhlbgogIGV4aXQgMQpmaQplY2hvICIjIS9iaW4vYmFzaAojIFVzZSB0aGUgbXBpcmFuayB0byBtYW5hZ2UgdGhlIGRldmljZToKJERJUl9OQU1FL2J1aWxkL2hpcC1zdHJlYW0gLS1kZXZpY2UgXCRPTVBJX0NPTU1fV09STERfUkFOSyAtbiA1MCAtcyAyNjg0MzU0NTYiID4gd3JhcHBlci5zaApjaG1vZCB1K3ggd3JhcHBlci5zaAo=