apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: install-linux-tools
  labels:
    primus-safe.display.name: "install-linux-tools"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  category: Tools
  description: linux-tools provides a set of advanced tools for system performance analysis, debugging, and tuning, which are typically closely related to the currently running kernel version
  action: bGludXhfdG9vbHM9ImxpbnV4LXRvb2xzLSQodW5hbWUgLXIpIgpkcGtnIC1sIHwgZ3JlcCAtcSAiJGxpbnV4X3Rvb2xzIgppZiBbICQ/IC1uZSAwIF07IHRoZW4KICBhcHQtZ2V0IHVwZGF0ZSA+L2Rldi9udWxsICYmIGFwdCBpbnN0YWxsIC15ICIkbGludXhfdG9vbHMiID4vZGV2L251bGwKICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgIGV4aXQgMQogIGZpCmZpCg==