apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: install-openmpi-bin
  labels:
    primus-safe.display.name: "install-openmpi-bin"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  category: Tools
  description: Open MPI is an open-source implementation of the Message Passing Interface. This package provides the installation of core executable tools of MPI.
  action: ZHBrZyAtbCB8IGdyZXAgLXEgb3Blbm1waS1iaW4KaWYgWyAkPyAtbmUgMCBdOyB0aGVuCiAgYXB0LWdldCB1cGRhdGUgPi9kZXYvbnVsbCAmJiBhcHQtZ2V0IC15IGluc3RhbGwgb3Blbm1waS1iaW4gb3Blbm1waS1jb21tb24gbGlib3Blbm1waS1kZXYgPi9kZXYvbnVsbAogIGlmIFsgJD8gLW5lIDAgXTsgdGhlbgogICAgZXhpdCAxCiAgZmkKZmkK