apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: install-roc-blas
  labels:
    primus-safe.display.name: "install-roc-blas"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: dpkg
  category: Tools
  description: The rocBLAS test application allows users to benchmark the GEMM performance of rocBLAS in a standalone application
  extensions:
    action: UkVQT19VUkw9Imh0dHBzOi8vZ2l0aHViLmNvbS9ST0NtL3JvY0JMQVMuZ2l0IgpESVJfTkFNRT0iL3Jvb3Qvcm9jQkxBUyIKaWYgWyAhIC1kICIkRElSX05BTUUiIF07IHRoZW4KICBkcGtnIC1sIHwgZ3JlcCAtcSBnaXQKICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgIGFwdC1nZXQgdXBkYXRlID4vZGV2L251bGwgJiYgYXB0LWdldCAteSBpbnN0YWxsIGdpdCA+L2Rldi9udWxsCiAgICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgICAgZXhpdCAxCiAgICBmaQogIGZpCiAgZ2l0IGNsb25lICIkUkVQT19VUkwiID4vZGV2L251bGwKICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgIGV4aXQgMQogIGZpCmZpCmNkICIkRElSX05BTUUiIHx8IGV4aXQgMQpnaXQgY2hlY2tvdXQgcm9jbS02LjIuMCA+L2Rldi9udWxsICYmIGNobW9kICt4IC4vaW5zdGFsbC5zaCAmJiAuL2luc3RhbGwuc2ggLS1jbGllbnRzLW9ubHkgLS1saWJyYXJ5LXBhdGggL29wdC9yb2NtID4vZGV2L251bGwKaWYgWyAkPyAtbmUgMCBdOyB0aGVuCiAgZXhpdCAxCmZpCg==