apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: install-transfer-bench
  labels:
    primus-safe.display.name: "install-transfer-bench"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: dpkg
  category: Tools
  description: TransferBench is a tool and utility for benchmarking copies between user-specified CPU and GPU devices
  extensions:
    action: UkVQT19VUkw9Imh0dHBzOi8vZ2l0aHViLmNvbS9ST0NtL1RyYW5zZmVyQmVuY2guZ2l0IgpESVJfTkFNRT0iL3Jvb3QvVHJhbnNmZXJCZW5jaCIKaWYgWyAhIC1kICIkRElSX05BTUUiIF07IHRoZW4KICBkcGtnIC1sIHwgZ3JlcCAtcSBnaXQKICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgIGFwdC1nZXQgdXBkYXRlID4vZGV2L251bGwgJiYgYXB0LWdldCAteSBpbnN0YWxsIGdpdCA+L2Rldi9udWxsCiAgICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgICAgZXhpdCAxCiAgICBmaQogIGZpCiAgZ2l0IGNsb25lICIkUkVQT19VUkwiID4vZGV2L251bGwKICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgIGV4aXQgMQogIGZpCmZpCmNkICIkRElSX05BTUUiIHx8IGV4aXQgMQpkcGtnIC1sIHwgZ3JlcCAtcSBtYWtlCmlmIFsgJD8gLW5lIDAgXTsgdGhlbgogIGFwdC1nZXQgdXBkYXRlID4vZGV2L251bGwgJiYgYXB0LWdldCAteSBpbnN0YWxsIG1ha2UgPi9kZXYvbnVsbAogIGlmIFsgJD8gLW5lIDAgXTsgdGhlbgogICAgZXhpdCAxCiAgZmkKZmkKQ0M9aGlwY2MgbWFrZSA+IC9kZXYvbnVsbAppZiBbICQ/IC1uZSAwIF07IHRoZW4KICBleGl0IDEKZmkK