apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: install-libgtest
  labels:
    primus-safe.display.name: "install-libgtest-dev"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  category: Tools
  description: libgtest-dev provides the development files of the Google Test (GTest) framework, used for writing and running unit tests in C++ projects.
  action: ZHBrZyAtbCB8IGdyZXAgLXEgImxpYmd0ZXN0LWRldiIKaWYgWyAkPyAtbmUgMCBdOyB0aGVuCiAgYXB0LWdldCB1cGRhdGUgPi9kZXYvbnVsbCAmJiBhcHQgaW5zdGFsbCAteSBsaWJndGVzdC1kZXYgPi9kZXYvbnVsbAogIGlmIFsgJD8gLW5lIDAgXTsgdGhlbgogICAgZXhpdCAxCiAgZmkKZmkK