apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: install-babel-stream
  labels:
    primus-safe.display.name: "install-babel-stream"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  category: Tools
  description: BabelStream is an open-source benchmark to measure transfer rates to/from global device memory on GPUs
  action: UkVQT19VUkw9Imh0dHBzOi8vZ2l0aHViLmNvbS9Vb0ItSFBDL0JhYmVsU3RyZWFtLmdpdCIKRElSX05BTUU9Ii9yb290L0JhYmVsU3RyZWFtIgppZiBbIC1kICIkRElSX05BTUUiIF07IHRoZW4KICBleGl0IDAKZmkKCmRwa2cgLWwgfCBncmVwIC1xIGdpdAppZiBbICQ/IC1uZSAwIF07IHRoZW4KICBhcHQtZ2V0IHVwZGF0ZSA+L2Rldi9udWxsICYmIGFwdC1nZXQgLXkgaW5zdGFsbCBnaXQgPi9kZXYvbnVsbAogIGlmIFsgJD8gLW5lIDAgXTsgdGhlbgogICAgZXhpdCAxCiAgZmkKZmkKZ2l0IGNsb25lICIkUkVQT19VUkwiID4vZGV2L251bGwKaWYgWyAkPyAtbmUgMCBdOyB0aGVuCiAgZXhpdCAxCmZpCgpjZCAiJERJUl9OQU1FIiB8fCBleGl0IDEKZHBrZyAtbCB8IGdyZXAgLXEgY21ha2UKaWYgWyAkPyAtbmUgMCBdOyB0aGVuCiAgYXB0LWdldCB1cGRhdGUgPi9kZXYvbnVsbCAmJiBhcHQtZ2V0IC15IGluc3RhbGwgY21ha2UgPi9kZXYvbnVsbAogIGlmIFsgJD8gLW5lIDAgXTsgdGhlbgogICAgZXhpdCAxCiAgZmkKZmkKY21ha2UgLUJidWlsZCAtSC4gLURNT0RFTD1oaXAgLURDTUFLRV9DWFhfQ09NUElMRVI9aGlwY2MgPi9kZXYvbnVsbCAmJiBjbWFrZSAtLWJ1aWxkIGJ1aWxkID4vZGV2L251bGwKaWYgWyAkPyAtbmUgMCBdOyB0aGVuCiAgZXhpdCAxCmZpCmVjaG8gIiMhL2Jpbi9iYXNoCiMgVXNlIHRoZSBtcGlyYW5rIHRvIG1hbmFnZSB0aGUgZGV2aWNlOgokRElSX05BTUUvYnVpbGQvaGlwLXN0cmVhbSAtLWRldmljZSBcJE9NUElfQ09NTV9XT1JMRF9SQU5LIC1uIDUwIC1zIDI2ODQzNTQ1NiIgPiB3cmFwcGVyLnNoCmNobW9kIHUreCB3cmFwcGVyLnNoCg==