apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: install-rccl
  labels:
    primus-safe.display.name: "install-rccl"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: dpkg
  category: Tools
  description: RCCL is designed to be used as a performant backend for downstream applications, particularly AI training and inference workloads, it also has a test suite to benchmark and validate performance
  extensions:
    action: UkVQT19VUkw9Imh0dHBzOi8vZ2l0aHViLmNvbS9ST0NtL3JjY2wtdGVzdHMuZ2l0IgpESVJfTkFNRT0iL3Jvb3QvcmNjbC10ZXN0cyIKaWYgWyAhIC1kICIkRElSX05BTUUiIF07IHRoZW4KICBkcGtnIC1sIHwgZ3JlcCAtcSBnaXQKICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgIGFwdC1nZXQgdXBkYXRlID4vZGV2L251bGwgJiYgYXB0LWdldCAteSBpbnN0YWxsIGdpdCA+L2Rldi9udWxsCiAgICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgICAgZXhpdCAxCiAgICBmaQogIGZpCiAgZ2l0IGNsb25lICIkUkVQT19VUkwiID4vZGV2L251bGwKICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgIGV4aXQgMQogIGZpCmZpCmNkICIkRElSX05BTUUiIHx8IGV4aXQgMQpkcGtnIC1sIHwgZ3JlcCAtcSBtYWtlCmlmIFsgJD8gLW5lIDAgXTsgdGhlbgogIGFwdC1nZXQgdXBkYXRlID4vZGV2L251bGwgJiYgYXB0LWdldCAteSBpbnN0YWxsIG1ha2UgPi9kZXYvbnVsbAogIGlmIFsgJD8gLW5lIDAgXTsgdGhlbgogICAgZXhpdCAxCiAgZmkKZmkKbWFrZSBOQ0NMX0hPTUU9L29wdC9yb2NtLyA+L2Rldi9udWxsCmlmIFsgJD8gLW5lIDAgXTsgdGhlbgogIGV4aXQgMQpmaQo=