apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: install-rocm-validation
  labels:
    primus-safe.display.name: "install-rocm-validation-suite"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  category: Tools
  description: rocminfo is a command-line tool provided by the ROCm (Radeon Open Compute) platform, used for diagnosing, debugging, and verifying whether the ROCm environment is correctly installed and configured
  action: ZHBrZyAtbCB8IGdyZXAgLXEgcm9jbS12YWxpZGF0aW9uLXN1aXRlCmlmIFsgJD8gLW5lIDAgXTsgdGhlbgogIGFwdC1nZXQgdXBkYXRlID4vZGV2L251bGwgJiYgYXB0IGluc3RhbGwgLXkgcm9jbS12YWxpZGF0aW9uLXN1aXRlID4vZGV2L251bGwKICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgIGV4aXQgMQogIGZpCmZpCg==