#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: load-rdma-module
  labels:
    primus-safe.display.name: "load-rdma-module"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  category: Net
  required: true
  description: Load the RDMA module on a Linux system
  action: c3lzdGVtZF9wYXRoPSIvZXRjL3N5c3RlbWQvc3lzdGVtIgpzeXN0ZW1kX3NjcmlwdD0iJHN5c3RlbWRfcGF0aC9sb2FkLXJkbWEtbW9kdWxlLnNoIgpzeXN0ZW1kX3NlcnZpY2VfbmFtZT0ibG9hZC1yZG1hLW1vZHVsZS5zZXJ2aWNlIgpzeXN0ZW1kX3NlcnZpY2VfcGF0aD0iJHN5c3RlbWRfcGF0aC8kc3lzdGVtZF9zZXJ2aWNlX25hbWUiCgppZiBbICEgLWYgIiRzeXN0ZW1kX3NjcmlwdCIgXTsgdGhlbgogIGVjaG8gIiMhL2Jpbi9zaAptb2Rwcm9iZSBpYl91bWFkIiA+ICRzeXN0ZW1kX3NjcmlwdAogIGNobW9kICt4ICIkc3lzdGVtZF9zY3JpcHQiCmZpCmlmIFsgLWYgIiRzeXN0ZW1kX3NlcnZpY2VfcGF0aCIgXTsgdGhlbgogIGV4aXQgMApmaQoKY2F0ID4gIiRzeXN0ZW1kX3NlcnZpY2VfcGF0aCIgPDwgJ0VPRicKW1VuaXRdCkRlc2NyaXB0aW9uPUF1dG8gbG9hZCByZG1hIApBZnRlcj1uZXR3b3JrLnRhcmdldAoKW1NlcnZpY2VdClR5cGU9b25lc2hvdApFeGVjU3RhcnQ9L2Jpbi9zaCAvZXRjL3N5c3RlbWQvc3lzdGVtL2xvYWQtcmRtYS1tb2R1bGUuc2gKUmVtYWluQWZ0ZXJFeGl0PXllcwoKW0luc3RhbGxdCldhbnRlZEJ5PW11bHRpLXVzZXIudGFyZ2V0CkVPRgoKc3lzdGVtY3RsIGRhZW1vbi1yZWxvYWQgJiYgc3lzdGVtY3RsIGVuYWJsZSAiJHN5c3RlbWRfc2VydmljZV9uYW1lIiAmJiBzeXN0ZW1jdGwgc3RhcnQgIiRzeXN0ZW1kX3NlcnZpY2VfbmFtZSIKZXhpdCAkPwo=