apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: sysctl-ulimit
  labels:
    primus-safe.display.name: "sysctl-ulimit-65535"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: config
  category: System
  description: Set max open files per user process to 65535
  extensions:
    observe: Z3JlcCAtcSBeIiogaGFyZCBub2ZpbGUgNjU1MzUiICIvZXRjL3NlY3VyaXR5L2xpbWl0cy5jb25mIgpleGl0ICQ/Cg==
    action: ZWNobyAiKiBzb2Z0IG5vZmlsZSA2NTUzNSIgPj4gL2V0Yy9zZWN1cml0eS9saW1pdHMuY29uZgplY2hvICIqIGhhcmQgbm9maWxlIDY1NTM1IiA+PiAvZXRjL3NlY3VyaXR5L2xpbWl0cy5jb25mCg==