apiVersion: amd.com/v1
kind: User
metadata:
  name: root
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: default
  roles:
    - system-admin