apiVersion: v2
name: primus-lens-kube-state-metrics
description: Kube State Metrics wrapper chart
type: application
version: 1.0.0
appVersion: "5.27.0"

dependencies:
  - name: kube-state-metrics
    version: "5.27.0"
    repository: https://prometheus-community.github.io/helm-charts
