# The parameters should be modified according to the actual cluster environment.
apiVersion: amd.com/v1
kind: NodeFlavor
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: amd-mi325x-example
spec:
  cpu:
    product: AMD_EPYC_9575F
    quantity: "128"
  dataDisk:
    count: 4
    quantity: 3.49Ti
    type: nvme
  extendedResources:
    ephemeral-storage: 13496617142Ki
    rdma/hca: 1k
  gpu:
    product: AMD_Instinct_MI325X
    quantity: "8"
    resourceName: amd.com/gpu
  memory: 3169200176Ki
  rootDisk:
    count: 1
    quantity: 14Ti
    type: nvme
