#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

apiVersion: batch/v1
kind: Job
metadata:
  name: generate-image-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        app: image-secret-generator
    spec:
      activeDeadlineSeconds: 300
      restartPolicy: OnFailure
      serviceAccountName: secret-manager
      containers:
        - name: generate-key
          image: docker.io/primussafe/kubectl:latest
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              set -e
              if kubectl -n {{ .Release.Namespace }} get secret {{ .Release.Name }}-image > /dev/null 2>&1; then
                echo "Secret already exists. Skipping image secret generation."
                exit 0
              fi

              cat <<EOF > /tmp/secret.yaml
              apiVersion: v1
              data:
                .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsiYXV0aCI6ImNISnBiWFZ6TFhOaFptVkFiM1YwYkc5dmF5NWpiMjA2UVcxRVdXVlRJVUFqIn0sImhhcmJvci50dzMyNS5wcmltdXMtc2FmZS5hbWQuY29tIjp7ImF1dGgiOiJZV1J0YVc0NlFXMUVXV1ZUSVVBaiJ9fX0=
              kind: Secret
              metadata:
                name: {{ .Release.Name }}-image
                namespace: {{ .Release.Namespace }}
                labels:
                  primus-safe.display.name: {{ .Release.Name }}-image
                  primus-safe.secret.all.workspace: "true"
                  primus-safe.secret.type: image
                  app.kubernetes.io/managed-by: Helm
                annotations:
                  meta.helm.sh/release-name: {{ .Release.Name }}
                  meta.helm.sh/release-namespace: {{ .Release.Namespace }}
              type: kubernetes.io/dockerconfigjson
              EOF

              kubectl apply -f /tmp/secret.yaml
              echo "create image secret successfully"
              exit 0