#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#
{{- if .Values.grafana.enable }}
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    system: primus-safe
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  config:
    paths:
      data: /var/lib/grafana/
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: "true"
    log:
      mode: console
    grafana_net:
      url: https://grafana.net
    server:
      domain: "127.0.0.1"
      root_url: "http://127.0.0.1:30183/grafana"
      serve_from_sub_path: "true"
    security:
      allow_embedding: "true"
    auth.anonymous:
      enabled: "true"
  persistentVolumeClaim:
    spec:
      accessModes:
        - "{{ if eq .Values.global.storage_class "juicefs" }}ReadWriteMany{{ else }}ReadWriteOnce{{ end }}"
      resources:
        requests:
          storage: 1Gi
      storageClassName: "{{ .Values.global.storage_class }}"
{{- end }}