# Copyright 2017 - 2025 Crunchy Data Solutions, Inc.
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "install.roleBindingKind" . }}
metadata:
  name: {{ include "install.roleBindingName" . }}
  labels:
    {{- include "install.labels" . | nindent 4 }}
    {{- include "install.clusterLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ include "install.roleKind" . }}
  name: {{ include "install.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "install.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
