apiVersion: apps/v1
kind: Deployment
metadata:
  name: primus-safe-resource-manager
  namespace: primus-safe
  labels:
    app: primus-safe-resource-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: primus-safe-resource-manager
  template:
    metadata:
      labels:
        app: primus-safe-resource-manager
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: DoesNotExist
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: NotIn
                    values:
                      - "true"
      serviceAccountName: primus-safe-manager
      containers:
        - name: primus-safe-resource-manager
          image: /primus-safe/resource-manager:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "/opt/primus-safe/resource-manager/run.sh"]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: crypto_file
              value: /etc/secrets/key
          volumeMounts:
            - name: primus-safe-secret
              mountPath: /etc/secrets
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 2
          resources:
            limits:
              cpu: "8000m"
              memory: 16Gi
            requests:
              cpu: "8000m"
              memory: 16Gi
      volumes:
        - name: primus-safe-secret
          secret:
            secretName: primus-safe-secret
      terminationGracePeriodSeconds: 10
      priorityClassName: system-cluster-critical
      restartPolicy: Always
