{{- if and (eq (include "primus-lens.data.enabled" .) "true") .Values.data.nodeExporter.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: {{ include "primus-lens.fullname" . }}-node-exporter
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "primus-lens.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: node-exporter
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 30s
{{- end }}

