#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  labels:
    primus-safe.display.name: "kuberay-operator-1.4.2"
    app.kubernetes.io/managed-by: Helm
    primus-safe.addon.default: ""
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: kuberay-operator-1.4.2
spec:
  category: plugin
  description: KubeRay is a Kubernetes operator that simplifies the deployment and management of Ray applications on Kubernetes.
  url: oci://registry-1.docker.io/primussafe/kuberay-operator
  version: 1.4.2
  type: helm
  helmDefaultNamespace: ray-system