#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#
{{- if eq .Values.net.ingress "higress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    higress.io/resource-definer: higress
    higress.io/domain_{{ .Values.global.sub_domain }}.{{ .Values.global.domain }}: "true"
  annotations:
    higress.io/destination: {{ .Release.Name }}-web.{{ .Release.Namespace }}.svc.cluster.local:80
    higress.io/ignore-path-case: "false"
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    higress.io/proxy-http-version: "1.1"
    higress.io/request-set-header: |
      Upgrade $http_upgrade
      Connection "upgrade"
      X-Forwarded-For $proxy_add_x_forwarded_for
      X-Forwarded-Proto $scheme
    higress.io/timeout: "3600"
    higress.io/upstream-keepalive-time: 1h
    higress.io/upstream-keepalive-timeout: "3600"
    higress.io/websocket-enable: "true"
spec:
  ingressClassName: higress
  rules:
    - host: {{ .Values.global.sub_domain }}.{{ .Values.global.domain }}
      http:
        paths:
          - backend:
              resource:
                apiGroup: networking.higress.io
                kind: McpBridge
                name: default
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.global.sub_domain }}.{{ .Values.global.domain }}
      secretName: default
{{- end }}