apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: perf-cpu
  labels:
    primus-safe.display.name: "perf-cpu"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: validation
  category: System
  description: Use the perf tool to test CPU performance
  extensions:
    action: ZHBrZyAtbCB8IGdyZXAgLXEgImxpbnV4LXRvb2xzLSQodW5hbWUgLXIpIgppZiBbICQ/IC1uZSAwIF07IHRoZW4KICBhcHQtZ2V0IHVwZGF0ZSA+L2Rldi9udWxsIDI+JjEKICBhcHQgaW5zdGFsbCAteSBsaW51eC10b29scy0kKHVuYW1lIC1yKSBsaW51eC1jbG91ZC10b29scy0kKHVuYW1lIC1yKSA+L2Rldi9udWxsIDI+ZXJyb3IKICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgIGNhdCBlcnJvciAmJiBybSAtZiBlcnJvcgogICAgZWNobyAiW0VSUk9SXTogZmFpbGVkIHRvIGluc3RhbGwgbGludXgtdG9vbHMiCiAgICBleGl0IDEKICBmaQogIHJtIC1mIGVycm9yCmZpCgpMT0dfRklMRT0iL3RtcC9wZXJmX2NwdS5sb2ciCnBlcmYgc3RhdCAtZSBjeWNsZXMsaW5zdHJ1Y3Rpb25zLGNhY2hlLW1pc3NlcyAtYSAtciAxMCAtLSBzbGVlcCAzID4kTE9HX0ZJTEUgMj4mMQpFWElUX0NPREU9JD8KaWYgWyAkRVhJVF9DT0RFIC1uZSAwIF07IHRoZW4KICBjYXQgIiRMT0dfRklMRSIgJiYgcm0gLWYgJExPR19GSUxFCiAgZWNobyAiW0VSUk9SXTogcGVyZiBmYWlsZWQgd2l0aCBleGl0IGNvZGU6ICRFWElUX0NPREUiCiAgZXhpdCAxCmZpCgppbnNuX3Blcl9jeWNsZT0kKGdyZXAgJ2luc24gcGVyIGN5Y2xlJyAkTE9HX0ZJTEUgfCBhd2sgJ3tmb3IoaT0xO2k8PU5GO2krKyl7aWYoJGk9PSJpbnNuIikgcHJpbnQgJChpLTEpfX0nKQppZiBbWyAtbiAiJGluc25fcGVyX2N5Y2xlIiBdXTsgdGhlbgogIGVjaG8gIltJTkZPXSBpbnNuIHBlciBjeWNsZSA9ICRpbnNuX3Blcl9jeWNsZSIKZWxzZQogIGVjaG8gIltFUlJPUl0gZmFpbGVkIHRvIGdldCBpbnNuIHBlciBjeWNsZSIKICBleGl0IDEKZmkKdGhyZXNob2xkPTEKaXNfZ3JlYXRlcj0kKGVjaG8gIiRpbnNuX3Blcl9jeWNsZSA+PSAkdGhyZXNob2xkIiB8IGJjIC1sKQppZiBbWyAiJGlzX2dyZWF0ZXIiIC1uZSAxIF1dOyB0aGVuCiAgZWNobyAiW0VSUk9SXSBpbnNuIHBlciBjeWNsZSgkaW5zbl9wZXJfY3ljbGUpIGlzIGxlc3MgdGhhbiB0aGUgdGhyZXNob2xkKCR0aHJlc2hvbGQpIgogIGV4aXQgMQpmaQplY2hvICJbU1VDQ0VTU10gcGVyZiBjcHUgdGVzdCBwYXNzZWQgc3VjY2Vzc2Z1bGx5IgpleGl0IDAK
