apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: rvs-pcie-quality
  labels:
    primus-safe.display.name: "rvs-pcie-quality"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: validation
  category: System
  gpuChip: amd
  description: Use the command "rvs -c peqt_single.conf" to qualify the PCIe bus which the GPU is connected to.
  extensions:
    action: ZHBrZyAtbCB8IGdyZXAgLXEgcm9jbS12YWxpZGF0aW9uLXN1aXRlCmlmIFsgJD8gLW5lIDAgXTsgdGhlbgogIGFwdC1nZXQgdXBkYXRlID4vZGV2L251bGwgMj4mMQogIGFwdCBpbnN0YWxsIC15IHJvY20tdmFsaWRhdGlvbi1zdWl0ZSA+L2Rldi9udWxsIDI+ZXJyb3IKICBpZiBbICQ/IC1uZSAwIF07IHRoZW4KICAgIGNhdCBlcnJvciAmJiBybSAtZiBlcnJvcgogICAgZWNobyAiW0VSUk9SXSBmYWlsZWQgdG8gaW5zdGFsbCByb2NtLXZhbGlkYXRpb24tc3VpdGUiCiAgICBleGl0IDEKICBmaQogIHJtIC1mIGVycm9yCmZpCgpleHBvcnQgUEFUSD0kUEFUSDovb3B0L3JvY20vYmluCmV4cG9ydCBSVlNfQ09ORj0vb3B0L3JvY20vc2hhcmUvcm9jbS12YWxpZGF0aW9uLXN1aXRlL2NvbmYKTE9HX0ZJTEU9Ii90bXAvcGNpZV9xdWFsaXR5LmxvZyIKcnZzIC1jICIke1JWU19DT05GfS9wZXF0X3NpbmdsZS5jb25mIiA+JExPR19GSUxFIDI+JjEKRVhJVF9DT0RFPSQ/CmlmIFsgJEVYSVRfQ09ERSAtbmUgMCBdOyB0aGVuCiAgY2F0ICRMT0dfRklMRSAmJiBybSAtZiAkTE9HX0ZJTEUKICBlY2hvICJbRVJST1JdIHJ2cyBjb21tYW5kIGZhaWxlZCB3aXRoIGV4aXQgY29kZTogJEVYSVRfQ09ERSIKICBleGl0IDEKZmkKCnRvdGFsPTAKZm9yIGkgaW4gezEuLjE3fTsgZG8KICAgIGFjdGlvbj0iW3BjaWVfYWN0XyRpXSBwZXF0IHRydWUiCiAgICBpZiBncmVwIC1xRiAiJGFjdGlvbiIgIiRMT0dfRklMRSI7IHRoZW4KICAgICAgICAoKHRvdGFsKyspKQogICAgZWxzZQogICAgICAgIGVjaG8gIltFUlJPUl06ICRhY3Rpb24gbm90IGZvdW5kIgoJcm0gLWYgJExPR19GSUxFCglleGl0IDEKICAgIGZpCmRvbmUKZWNobyAiW1NVQ0NFU1NdOiB0b3RhbCAkdG90YWwgcGNpZV9hY3QgcGFzc2VkIgpybSAtZiAkTE9HX0ZJTEUKZXhpdCAwCg==
