apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: rvs-gpu-property
  labels:
    primus-safe.display.name: "rvs-gpu-property"
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: validation
  category: System
  gpuChip: amd
  description: Use the command "rvs -c gpup_single.conf" to validate GPU properties.
  extensions:
    action: ZHBrZyAtbCB8IGdyZXAgLXEgcm9jbS12YWxpZGF0aW9uLXN1aXRlCmlmIFsgJD8gLW5lIDAgXTsgdGhlbgogIGFwdC1nZXQgdXBkYXRlID4vZGV2L251bGwgMj4mMQogIGFwdCBpbnN0YWxsIC15IHJvY20tdmFsaWRhdGlvbi1zdWl0ZT4vZGV2L251bGwgMj5lcnJvcgogIGlmIFsgJD8gLW5lIDAgXTsgdGhlbgogICAgY2F0IGVycm9yICYmIHJtIC1mIGVycm9yCiAgICBlY2hvICJbRVJST1JdIGZhaWxlZCB0byBpbnN0YWxsIHJvY20tdmFsaWRhdGlvbi1zdWl0ZSIKICAgIGV4aXQgMQogIGZpCiAgcm0gLWYgZXJyb3IKZmkKZXhwb3J0IFBBVEg9JFBBVEg6L29wdC9yb2NtL2JpbgpleHBvcnQgUlZTX0NPTkY9L29wdC9yb2NtL3NoYXJlL3JvY20tdmFsaWRhdGlvbi1zdWl0ZS9jb25mCk9VVFBVVD0kKHJ2cyAtYyAiJHtSVlNfQ09ORn0vZ3B1cF9zaW5nbGUuY29uZiIgMj4mMSkKRVhJVF9DT0RFPSQ/CmlmIFsgJEVYSVRfQ09ERSAtbmUgMCBdOyB0aGVuCiAgZWNobyAiJE9VVFBVVCIKICBlY2hvICJbRVJST1JdIHJ2cyBjb21tYW5kIGZhaWxlZCB3aXRoIGV4aXQgY29kZTogJEVYSVRfQ09ERSIKICBleGl0IDEKZmkKaWYgZWNobyAiJE9VVFBVVCIgfCBncmVwIC1pICJlcnJvciIgPiAvZGV2L251bGw7IHRoZW4KICBlY2hvICIkT1VUUFVUIgogIGVjaG8gIltFUlJPUl0gRm91bmQgJ2Vycm9yJyBpbiBvdXRwdXQuIgogIGV4aXQgMQpmaQplY2hvICJbU1VDQ0VTU10gcnZzIC1jIGdwdXBfc2luZ2xlLmNvbmYgc3VjY2Vzc2Z1bGx5IgpleGl0IDAK
