#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-apiserver
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.apiserver.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-apiserver
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-apiserver
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: NotIn
                    values:
                      - "true"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Release.Name }}-job-manager
                        - {{ .Release.Name }}-webhooks
                        - {{ .Release.Name }}-resource-manager
                        - {{ .Release.Name }}-web
                topologyKey: kubernetes.io/hostname
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}-apiserver
          image: {{ .Values.global.image_registry }}/primussafe/{{ .Values.apiserver.image }}
          imagePullPolicy: Always
          command: ["/bin/sh", "/opt/primus-safe/apiserver/run.sh"]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: crypto-secret
              mountPath: {{ default "/etc/secrets/crypto" (default .Values.crypto).secret_path }}
              readOnly: true
            - name: server-config
              mountPath: /opt/primus-safe/apiserver/config
              readOnly: true
            {{- if .Values.db.enable }}
            - name: db-secret
              mountPath: {{ default "/etc/secrets/db" (default .Values.db).secret_path }}
              readOnly: true
            {{- end }}
            {{- if and .Values.opensearch.enable (or (empty .Values.opensearch.username) (empty .Values.opensearch.password)) }}
            - name: opensearch-secret
              mountPath: {{ .Values.opensearch.secret_path }}
              readOnly: true
            {{- end }}
            {{- if .Values.ssh.enable }}
            - name: ssh-proxy
              mountPath: {{ default "/etc/secrets/ssh" (default .Values.ssh).secret_path }}
              readOnly: true
            {{- end }}
            {{- if .Values.s3.enable }}
            - name: s3-secret
              mountPath: {{ .Values.s3.secret_path }}
              readOnly: true
            {{- end }}
          ports:
            - containerPort: {{ default 8088 (default .Values.apiserver).port }}
              name: http-port
            {{- if .Values.ssh.enable }}
            - containerPort: {{ default 2222 (default .Values.ssh).port }}
              name: ssh-port
              protocol: TCP
            {{- end }}
          {{- if default true (default .Values.k8s).enable_health_check }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ default 8082 (default .Values.apiserver).health_port }}
            initialDelaySeconds: 20
            periodSeconds: 2
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ default 8082 (default .Values.apiserver).health_port }}
            initialDelaySeconds: 20
            periodSeconds: 2
            timeoutSeconds: 3
          {{- end }}
          resources:
            limits:
              cpu: {{ .Values.apiserver.cpu }}
              memory: {{ .Values.apiserver.memory }}
            requests:
              cpu: {{ .Values.apiserver.cpu }}
              memory: {{ .Values.apiserver.memory }}
      volumes:
        - name: crypto-secret
          secret:
            secretName: {{ .Release.Name }}-crypto
        {{- if .Values.db.enable }}
        - name: db-secret
          secret:
            secretName: {{ .Release.Name }}-pguser-{{ .Release.Name }}
        {{- end }}
        {{- if and .Values.opensearch.enable (or (empty .Values.opensearch.username) (empty .Values.opensearch.password)) }}
        - name: opensearch-secret
          secret:
            secretName: {{ .Values.opensearch.secret }}
        {{- end }}
        {{- if .Values.ssh.enable }}
        - name: ssh-proxy
          secret:
            secretName: {{ .Release.Name }}-ssh-proxy
        {{- end }}
        {{- if .Values.s3.enable }}
        - name: s3-secret
          secret:
            secretName: {{ .Values.s3.secret }}
        {{- end }}
        - name: server-config
          configMap:
            name: {{ .Release.Name }}-apiserver
      {{- if .Values.global.image_pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.global.image_pull_secret }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      priorityClassName: system-cluster-critical
      restartPolicy: Always
