{{- if and (eq (include "primus-lens.management.enabled" .) "true") .Values.management.grafana.enabled }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ include "primus-lens.fullname" . }}-victoria metrics
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "primus-lens.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana-datasource
spec:
  instanceSelector:
    matchLabels:
      {{- include "primus-lens.selectorLabels" . | nindent 6 }}
  
  datasource:
    name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: {{ include "primus-lens.victoriametricsURL" . }}
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: "30s"
{{- end }}

