{{- if and (eq (include "primus-lens.management.enabled" .) "true") .Values.management.grafana.enabled (eq .Values.management.grafana.accessType "ingress") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "primus-lens.fullname" . }}-grafana
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "primus-lens.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.management.grafana.domain }}
    http:
      paths:
      - path: /grafana(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "primus-lens.fullname" . }}-grafana-service
            port:
              number: 3000
{{- end }}

