apiVersion: batch/v1
kind: Job
metadata:
  # The resources related to the hook need to be cleaned up, and they cannot be deleted directly.
  name: "delete-rbac"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: main
          image: {{ .Values.repository }}/kubectl:latest
          command:
            - sh
            - -c
            - |
              if kubectl get ClusterRoleBinding secret-manager -o name >/dev/null 2>&1; then
                kubectl delete ClusterRoleBinding secret-manager
              fi

              if kubectl get ClusterRole secret-manager -o name >/dev/null 2>&1; then
                kubectl delete ClusterRole secret-manager
              fi

              if kubectl get ServiceAccount secret-manager -n {{ .Release.Namespace }} -o name >/dev/null 2>&1; then
                kubectl delete ServiceAccount secret-manager -n {{ .Release.Namespace }}
              fi
             