apiVersion: batch/v1
kind: Job
metadata:
  # The resources related to the hook need to be cleaned up, and they cannot be deleted directly.
  name: "delete-secrets"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: main
          image: {{ .Values.repository }}/kubectl:latest
          command:
            - sh
            - -c
            - |
              if kubectl get secret {{ .Values.s3.secret }} -n {{ .Release.Namespace }} -o name >/dev/null 2>&1; then
                kubectl delete secret {{ .Values.s3.secret }} -n {{ .Release.Namespace }}
              fi

              if kubectl get secret {{ .Values.log.secret }} -n {{ .Release.Namespace }} -o name >/dev/null 2>&1; then
                kubectl delete secret {{ .Values.log.secret }} -n {{ .Release.Namespace }}
              fi

              if kubectl get secret {{ .Release.Name }}-crypto -n {{ .Release.Namespace }} -o name >/dev/null 2>&1; then
                kubectl delete secret {{ .Release.Name }}-crypto -n {{ .Release.Namespace }}
              fi

              if kubectl get secret {{ .Release.Name }}-ssh-proxy -n {{ .Release.Namespace }} -o name >/dev/null 2>&1; then
                kubectl delete secret {{ .Release.Name }}-ssh-proxy -n {{ .Release.Namespace }}
              fi