#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

{{- if .Values.ssh.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: generate-ssh-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        app: ssh-key-generator
    spec:
      activeDeadlineSeconds: 300
      restartPolicy: OnFailure
      serviceAccountName: secret-manager
      initContainers:
        - name: generate-ssh-key
          image: docker.io/library/alpine:latest
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
             set -e
             apk add --no-cache openssh
             mkdir -p /keys
             echo "Generating SSH keys..."
             ssh-keygen -t rsa -b 4096 -f /keys/id_rsa -N ""
             ls -l /keys/
             chown -R 65532:65532 /keys
          volumeMounts:
            - name: keys
              mountPath: /keys
      containers:
        - name: write-secret
          image: docker.io/primussafe/kubectl:latest
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              set -e

              if kubectl -n {{ .Release.Namespace }} get secret {{ .Release.Name }}-ssh-proxy > /dev/null 2>&1; then
                echo "Secret already exists. Skipping password generation."
                exit 0
              fi

              if [ ! -f /keys/id_rsa ]; then
                echo "ERROR: id_rsa not found!" >&2
                exit 1
              fi
              if [ ! -f /keys/id_rsa.pub ]; then
                echo "ERROR: id_rsa.pub not found!" >&2
                exit 1
              fi

              ID_RSA=$(cat /keys/id_rsa | base64 | tr -d '\n')
              ID_RSA_PUB=$(cat /keys/id_rsa.pub | base64 | tr -d '\n')

              cat <<EOF > /tmp/secret.yaml
              apiVersion: v1
              kind: Secret
              metadata:
                name: {{ .Release.Name }}-ssh-proxy
                namespace: {{ .Release.Namespace }}
                annotations:
                  meta.helm.sh/release-name: {{ .Release.Name }}
                  meta.helm.sh/release-namespace: {{ .Release.Namespace }}
              type: Opaque
              data:
                id_rsa: $${ID_RSA}
                id_rsa.pub: $${ID_RSA_PUB}
              EOF

              kubectl apply -f /tmp/secret.yaml
              echo "create SSH secret successfully"
              exit 0
          volumeMounts:
            - name: keys
              mountPath: /keys
      volumes:
        - name: keys
          emptyDir: {}
{{- end }}