apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJwcmltdXMtc2FmZUBvdXRsb29rLmNvbSIsInBhc3N3b3JkIjoiQW1EWWVTIUAjIiwiZW1haWwiOiJwcmltdXMtc2FmZUBvdXRsb29rLmNvbSIsImF1dGgiOiJjSEpwYlhWekxYTmhabVZBYjNWMGJHOXZheTVqYjIwNlFXMUVXV1ZUIn19fQ==
kind: Secret
metadata:
  name: {{ .Release.Name }}-image
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJwcmltdXMtc2FmZUBvdXRsb29rLmNvbSIsInBhc3N3b3JkIjoiQW1EWWVTIUAjIiwiZW1haWwiOiJwcmltdXMtc2FmZUBvdXRsb29rLmNvbSIsImF1dGgiOiJjSEpwYlhWekxYTmhabVZBYjNWMGJHOXZheTVqYjIwNlFXMUVXV1ZUIn19fQ==
kind: Secret
metadata:
  name: {{ .Release.Name }}-image
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}