{{/*
Primus Lens Web Console Deployment
*/}}
{{- if .Values.apps.web.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lens.fullname" . }}-web
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "lens.labels" . | nindent 4 }}
    app: {{ include "lens.fullname" . }}-web
spec:
  replicas: {{ .Values.apps.web.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "lens.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "lens.fullname" . }}-web
        {{- include "lens.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: app
        image: "{{ .Values.global.imageRegistry.url }}/{{ .Values.apps.web.image }}"
        imagePullPolicy: {{ .Values.global.imageRegistry.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: {{ .Values.apps.web.containerPort | default 80 }}
          protocol: TCP
        {{- if .Values.apps.web.resources }}
        resources:
          {{- toYaml .Values.apps.web.resources | nindent 10 }}
        {{- end }}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lens.fullname" . }}-web
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "lens.labels" . | nindent 4 }}
    app: {{ include "lens.fullname" . }}-web
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.apps.web.service.port | default 80 }}
    targetPort: {{ .Values.apps.web.containerPort | default 80 }}
    protocol: TCP
  selector:
    app: {{ include "lens.fullname" . }}-web
{{- end }}
