apiVersion: amd.com/v1
kind: AddonTemplate
metadata:
  name: load-amdgpu-module
  labels:
    primus-safe.display.name: "load-amdgpu-module"
spec:
  type: systemd
  category: GPU
  chip: amd-gpu
  description: Load the AMD GPU module on a Linux system
  extensions:
    action: bW9kcHJvYmUgYW1kZ3B1Cg==