apiVersion: v1
kind: Service
metadata:
  # Please don't change this name casually
  name: webhook-service
  namespace: primus-safe
spec:
  selector:
    app: primus-safe-webhooks
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8084
  type: ClusterIP
