#
# Copyright (C) 2025-2025, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

node_agent:
  image: "node-agent:202510310930"
  image_registry: "docker.io"
  image_pull_secret: "primus-safe-image"
monitor:
  nccl_socket_ifname: "eno0"
  nccl_ib_hca: "rdma0,rdma1,rdma2,rdma3,rdma4,rdma5,rdma6,rdma7"
  gpu_driver: "6.12.12"
  rocm_version: "6.4"
  nfs_server: ""
  nfs_path: ""
  nfs_mount: ""
