apiVersion: v2
name: primus-lens-opensearch-operator
description: OpenSearch Operator wrapper chart
type: application
version: 1.0.0
appVersion: "2.6.0"

dependencies:
  - name: opensearch-operator
    version: "2.6.0"
    repository: https://opensearch-project.github.io/opensearch-k8s-operator/
