apiVersion: amd.com/v1
kind: NodeTemplate
metadata:
  name: node-template
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  addOnTemplates:
    - disable-os-upgrade
    - load-amdgpu-module
    - load-rdma-module
    - disable-numa-balancing