apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-job-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-job-manager
spec:
  replicas: {{ .Values.job_manager.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-job-manager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-job-manager
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: DoesNotExist
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: NotIn
                    values:
                      - "true"
      serviceAccountName: {{ .Release.Name }}-manager
      containers:
        - name: {{ .Release.Name }}-job-manager
          image: {{ .Values.repository }}/{{ .Values.job_manager.image }}
          imagePullPolicy: Always
          command: ["/bin/sh", "/opt/primus-safe/job-manager/run.sh"]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            {{- if .Values.crypto.enable }}
            - name: crypto-secret
              mountPath: {{ .Values.crypto.mount_path }}
              readOnly: true
            {{- end }}
            - name: server-config
              mountPath: /opt/primus-safe/job-manager/config
              readOnly: true
            {{- if .Values.ssh.enable }}
            - name: ssh-proxy
              mountPath: {{ .Values.ssh.mount_path }}
              readOnly: true
            {{- end }}
          {{- if .Values.k8s.enable_health_check }}
          ports:
            - containerPort: {{ .Values.job_manager.health_port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.job_manager.health_port }}
            initialDelaySeconds: 20
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.job_manager.health_port }}
            initialDelaySeconds: 20
            periodSeconds: 2
          {{- end }}
          resources:
            limits:
              cpu: {{ .Values.job_manager.cpu }}
              memory: {{ .Values.job_manager.memory }}
            requests:
              cpu: {{ .Values.job_manager.cpu }}
              memory: {{ .Values.job_manager.memory }}
      volumes:
        {{- if .Values.crypto.enable }}
        - name: crypto-secret
          secret:
            secretName: {{ .Release.Name }}-crypto
        {{- end }}
        - name: server-config
          configMap:
            name: {{ .Release.Name }}-job-manager
        {{- if .Values.ssh.enable }}
        - name: ssh-proxy
          secret:
            secretName: {{ .Release.Name }}-ssh-proxy
        {{- end }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-image
      terminationGracePeriodSeconds: 10
      priorityClassName: system-cluster-critical
      restartPolicy: Always
