apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-job-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-job-manager
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.job_manager.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-job-manager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-job-manager
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: DoesNotExist
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: NotIn
                    values:
                      - "true"
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}-job-manager
          image: docker.io/primussafe/{{ .Values.job_manager.image }}
          imagePullPolicy: Always
          command: ["/bin/sh", "/opt/primus-safe/job-manager/run.sh"]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: server-config
              mountPath: /opt/primus-safe/job-manager/config
              readOnly: true
            {{- if .Values.ssh.enable }}
            - name: ssh-proxy
              mountPath: {{ default "/etc/secrets/ssh" (default .Values.ssh).mount_path }}
              readOnly: true
            {{- end }}
          {{- if default true (default .Values.k8s).enable_health_check }}
          ports:
            - containerPort: {{ default 8083 (default .Values.job_manager).health_port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ default 8083 (default .Values.job_manager).health_port }}
            initialDelaySeconds: 20
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ default 8083 (default .Values.job_manager).health_port }}
            initialDelaySeconds: 20
            periodSeconds: 2
          {{- end }}
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 2000m
              memory: 4Gi
      volumes:
        - name: server-config
          configMap:
            name: {{ .Release.Name }}-job-manager
        {{- if .Values.ssh.enable }}
        - name: ssh-proxy
          secret:
            secretName: {{ .Release.Name }}-ssh-proxy
        {{- end }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-image
      terminationGracePeriodSeconds: 10
      priorityClassName: system-cluster-critical
      restartPolicy: Always
