apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-job-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-job-manager
spec:
  replicas: {{ .Values.job_manager.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-job-manager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-job-manager
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: DoesNotExist
            - weight: 100
              preference:
                matchExpressions:
                  - key: feature.node.kubernetes.io/amd-gpu
                    operator: NotIn
                    values:
                      - "true"
      serviceAccountName: {{ .Release.Name }}-manager
      containers:
        - name: {{ .Release.Name }}-job-manager
          image: {{ .Values.repository }}/job-manager:{{ .Values.job_manager.tag }}
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          command: ["/bin/sh", "/opt/primus-safe/job-manager/run.sh"]
          volumeMounts:
            - name: server-secret
              mountPath: {{ .Values.crypto.path }}
            - name: server-config
              mountPath: /opt/primus-safe/job-manager/config
          ports:
            - containerPort: 8083
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8083
            initialDelaySeconds: 20
            periodSeconds: 2
          resources:
            limits:
              cpu: "8000m"
              memory: 16Gi
            requests:
              cpu: "8000m"
              memory: 16Gi
      volumes:
        - name: server-secret
          secret:
            secretName: {{ .Release.Name }}
        - name: server-config
          configMap:
            name: {{ .Release.Name }}-job-manager
      imagePullSecrets:
        - name: {{ .Release.Name }}-image
      terminationGracePeriodSeconds: 10
      priorityClassName: system-cluster-critical
      restartPolicy: Always
